services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: motdepassefort
      MYSQL_DATABASE: seminaire
      MYSQL_USER: sogan
      MYSQL_PASSWORD: motdepasse
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:

